name: main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup Node@lts
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Download deps
        run: pnpm install

      - name: 🏗 Build
        run: pnpm build
        working-directory: packages/dotlottie-js

      - name: 🚀 Release
        uses: changesets/action@v1
        with:
          commit: 'chore: 🤖 update versions'
          title: 'chore: 🤖 update versions'
          publish: pnpm release:publish
          version: pnpm release:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
